// Closed M14.1 leaf-to-column mapping. No arbitrary metadata or raw payload storage.
export const runtimeColumns = [
  ['organisation_id', 'organisationId', 'native'],
  ['observation_id', 'observationId', 'native'],
  ['connection_id', 'sourceConnection.connectionId', 'native'],
  ['connection_system', 'sourceConnection.sourceSystemId', 'native'],
  ['source_system_id', 'sourceSystemId', 'native'],
  ['provider_code', 'providerCode', 'native'],
  ['configuration_version', 'sourceConfigurationVersion', 'native'],
  ['trace_id', 'traceId', 'native'],
  ['span_id', 'spanId', 'native'],
  ['source_event_key', 'sourceEventKey', 'native'],
  ['parent_state', 'parent.state', 'native'],
  ['parent_reason', 'parent.reason', 'native'],
  ['parent_span_id', 'parent.parentSpanId', 'native'],
  ['started_nano', 'startedAtUnixNano', 'decimal'],
  ['ended_nano_state', 'endedAtUnixNano.state', 'native'],
  ['ended_nano_reason', 'endedAtUnixNano.reason', 'native'],
  ['ended_nano_value', 'endedAtUnixNano.value', 'native'],
  ['source_observed_nano_state', 'sourceObservedAtUnixNano.state', 'native'],
  ['source_observed_nano_reason', 'sourceObservedAtUnixNano.reason', 'native'],
  ['source_observed_nano_value', 'sourceObservedAtUnixNano.value', 'native'],
  ['received_at', 'receivedAt', 'instant'],
  ['kind', 'kind', 'native'],
  ['operation', 'operation', 'native'],
  ['execution_scope', 'executionScope', 'native'],
  ['binding_state', 'binding.state', 'native'],
  ['unresolved_reason', 'binding.reason', 'native'],
  ['producer_identity', 'binding.coordinates.producerIdentity', 'native'],
  ['deployment_state', 'binding.coordinates.deploymentReference.state', 'native'],
  ['deployment_reason', 'binding.coordinates.deploymentReference.reason', 'native'],
  ['deployment_value', 'binding.coordinates.deploymentReference.value', 'native'],
  ['artifact_state', 'binding.coordinates.artifactDigest.state', 'native'],
  ['artifact_reason', 'binding.coordinates.artifactDigest.reason', 'native'],
  ['artifact_value', 'binding.coordinates.artifactDigest.value', 'native'],
  ['agent_version_id', 'binding.agentVersion.objectId', 'native'],
  ['agent_version_org', 'binding.agentVersion.organisationId', 'native'],
  ['agent_version_kind', 'binding.agentVersion.kind', 'native'],
  ['binding_id', 'binding.proof.deploymentBindingId', 'native'],
  ['binding_org', 'binding.proof.organisationId', 'native'],
  ['binding_connection', 'binding.proof.connectionId', 'native'],
  ['binding_method', 'binding.proof.method', 'native'],
  ['binding_version', 'binding.proof.version', 'native'],
  ['target_state', 'target.observed.state', 'native'],
  ['target_reason', 'target.observed.reason', 'native'],
  ['target_kind', 'target.observed.value.kind', 'native'],
  ['target_provider', 'target.observed.value.providerCode', 'native'],
  ['target_reference', 'target.observed.value.sourceReference', 'native'],
  ['canonical_target_state', 'target.canonical.state', 'native'],
  ['canonical_target_reason', 'target.canonical.reason', 'native'],
  ['target_object_id', 'target.canonical.value.canonicalObject.objectId', 'native'],
  ['target_org', 'target.canonical.value.canonicalObject.organisationId', 'native'],
  ['target_object_kind', 'target.canonical.value.canonicalObject.kind', 'native'],
  ['target_proof_method', 'target.canonical.value.proof.method', 'native'],
  ['target_proof_version', 'target.canonical.value.proof.version', 'native'],
  ['target_mapping_id', 'target.canonical.value.proof.mappingId', 'native'],
  ['target_proof_provider', 'target.canonical.value.proof.providerCode', 'native'],
  ['target_source_connection', 'target.canonical.value.proof.sourceObject.connectionId', 'native'],
  ['target_external_type', 'target.canonical.value.proof.sourceObject.externalType', 'native'],
  ['target_external_id', 'target.canonical.value.proof.sourceObject.externalId', 'native'],
  ['source_status', 'sourceStatus', 'native'],
  ['outcome_state', 'outcome.state', 'native'],
  ['outcome_reason', 'outcome.reason', 'native'],
  ['outcome_basis', 'outcome.basis', 'native'],
  ['duration_state', 'duration.state', 'native'],
  ['duration_reason', 'duration.reason', 'native'],
  ['duration_value', 'duration.value.value', 'decimal'],
  ['duration_unit', 'duration.value.unit', 'native'],
  ['duration_basis', 'duration.value.basis', 'native'],
  ['duration_method', 'duration.value.method.code', 'native'],
  ['duration_version', 'duration.value.method.version', 'native'],
  ['error_state', 'error.state', 'native'],
  ['error_reason', 'error.reason', 'native'],
  ['error_category', 'error.value.category', 'native'],
  ['error_code', 'error.value.code', 'native'],
  ['reported_model_state', 'reportedModel.state', 'native'],
  ['reported_model_reason', 'reportedModel.reason', 'native'],
  ['reported_model_value', 'reportedModel.value', 'native'],
  ['token_unit', 'tokens.unit', 'native'],
  ['tokens_input_state', 'tokens.input.state', 'native'],
  ['tokens_input_reason', 'tokens.input.reason', 'native'],
  ['tokens_input_value', 'tokens.input.value', 'native'],
  ['tokens_output_state', 'tokens.output.state', 'native'],
  ['tokens_output_reason', 'tokens.output.reason', 'native'],
  ['tokens_output_value', 'tokens.output.value', 'native'],
  ['tokens_total_state', 'tokens.total.state', 'native'],
  ['tokens_total_reason', 'tokens.total.reason', 'native'],
  ['tokens_total_value', 'tokens.total.value', 'native'],
  ['supplied_state', 'cost.supplied.state', 'native'],
  ['supplied_reason', 'cost.supplied.reason', 'native'],
  ['supplied_kind', 'cost.supplied.value.kind', 'native'],
  ['supplied_amount', 'cost.supplied.value.amount', 'decimal'],
  ['supplied_currency', 'cost.supplied.value.currency', 'native'],
  ['supplied_scope', 'cost.supplied.value.scope.kind', 'native'],
  ['supplied_observation', 'cost.supplied.value.scope.observationId', 'native'],
  ['supplied_evidence_org', 'cost.supplied.value.source.evidence.organisationId', 'native'],
  ['supplied_evidence_connection', 'cost.supplied.value.source.evidence.connectionId', 'native'],
  ['supplied_evidence_observation', 'cost.supplied.value.source.evidence.observationId', 'native'],
  ['charge_reference', 'cost.supplied.value.source.chargeReference', 'native'],
  ['derived_state', 'cost.derived.state', 'native'],
  ['derived_reason', 'cost.derived.reason', 'native'],
  ['derived_kind', 'cost.derived.value.kind', 'native'],
  ['derived_amount', 'cost.derived.value.amount', 'decimal'],
  ['derived_currency', 'cost.derived.value.currency', 'native'],
  ['derived_scope', 'cost.derived.value.scope.kind', 'native'],
  ['derived_observation', 'cost.derived.value.scope.observationId', 'native'],
  ['pricing_source', 'cost.derived.value.pricing.sourceReference', 'native'],
  ['pricing_version', 'cost.derived.value.pricing.version', 'native'],
  ['pricing_provider', 'cost.derived.value.pricing.providerCode', 'native'],
  ['pricing_model', 'cost.derived.value.pricing.modelReference', 'native'],
  ['pricing_tier', 'cost.derived.value.pricing.serviceTier', 'native'],
  ['pricing_from', 'cost.derived.value.pricing.effectiveFrom', 'instant'],
  ['pricing_until_state', 'cost.derived.value.pricing.effectiveUntil.state', 'native'],
  ['pricing_until_reason', 'cost.derived.value.pricing.effectiveUntil.reason', 'native'],
  ['pricing_until_value', 'cost.derived.value.pricing.effectiveUntil.value', 'instant'],
  ['input_rate', 'cost.derived.value.pricing.inputRate', 'decimal'],
  ['output_rate', 'cost.derived.value.pricing.outputRate', 'decimal'],
  ['rate_unit', 'cost.derived.value.pricing.rateUnit', 'native'],
  ['input_coverage', 'cost.derived.value.pricing.inputCoverage', 'native'],
  ['output_coverage', 'cost.derived.value.pricing.outputCoverage', 'native'],
  ['adjustments', 'cost.derived.value.pricing.adjustments', 'native'],
  ['usage_unit', 'cost.derived.value.usageInputs.unit', 'native'],
  ['usage_input', 'cost.derived.value.usageInputs.input', 'native'],
  ['usage_output', 'cost.derived.value.usageInputs.output', 'native'],
  ['calculation_method', 'cost.derived.value.calculation.method', 'native'],
  ['calculation_version', 'cost.derived.value.calculation.version', 'native'],
  ['rounding', 'cost.derived.value.calculation.rounding', 'native'],
  ['decimal_places', 'cost.derived.value.calculation.decimalPlaces', 'native'],
  ['rounding_stage', 'cost.derived.value.calculation.roundingStage', 'native'],
  ['principal_state', 'context.principal.state', 'native'],
  ['principal_reason', 'context.principal.reason', 'native'],
  ['principal_kind', 'context.principal.value.value.kind', 'native'],
  ['principal_provider', 'context.principal.value.value.providerCode', 'native'],
  ['principal_authority', 'context.principal.value.value.authorityReference', 'native'],
  ['principal_reference', 'context.principal.value.value.principalReference', 'native'],
  ['principal_evidence_org', 'context.principal.value.support.evidence.organisationId', 'native'],
  ['principal_evidence_connection', 'context.principal.value.support.evidence.connectionId', 'native'],
  ['principal_evidence_observation', 'context.principal.value.support.evidence.observationId', 'native'],
  ['principal_method', 'context.principal.value.support.method.code', 'native'],
  ['principal_version', 'context.principal.value.support.method.version', 'native'],
  ['environment_state', 'context.environment.state', 'native'],
  ['environment_reason', 'context.environment.reason', 'native'],
  ['environment_value', 'context.environment.value.value', 'native'],
  ['environment_evidence_org', 'context.environment.value.support.evidence.organisationId', 'native'],
  ['environment_evidence_connection', 'context.environment.value.support.evidence.connectionId', 'native'],
  ['environment_evidence_observation', 'context.environment.value.support.evidence.observationId', 'native'],
  ['environment_method', 'context.environment.value.support.method.code', 'native'],
  ['environment_version', 'context.environment.value.support.method.version', 'native'],
  ['network_state', 'context.network.state', 'native'],
  ['network_reason', 'context.network.reason', 'native'],
  ['network_reference', 'context.network.value.networkReference', 'native'],
  ['vpc_state', 'context.network.value.vpcReference.state', 'native'],
  ['vpc_reason', 'context.network.value.vpcReference.reason', 'native'],
  ['vpc_value', 'context.network.value.vpcReference.value', 'native'],
  ['network_evidence_org', 'context.network.value.support.evidence.organisationId', 'native'],
  ['network_evidence_connection', 'context.network.value.support.evidence.connectionId', 'native'],
  ['network_evidence_observation', 'context.network.value.support.evidence.observationId', 'native'],
  ['network_method', 'context.network.value.support.method.code', 'native'],
  ['network_version', 'context.network.value.support.method.version', 'native'],
  ['trust_state', 'provenance.trustState', 'native'],
  ['provenance_org', 'provenance.evidence.organisationId', 'native'],
  ['provenance_connection', 'provenance.evidence.connectionId', 'native'],
  ['provenance_observation', 'provenance.evidence.observationId', 'native'],
  ['method_code', 'provenance.method.code', 'native'],
  ['method_version', 'provenance.method.version', 'native'],
  ['adapter_version', 'provenance.adapterVersion', 'native'],
  ['schema_version', 'provenance.schemaVersion', 'native'],
  ['mapping_version', 'provenance.mappingVersion', 'native'],
  ['instrumentation_name', 'provenance.instrumentation.name', 'native'],
  ['instrumentation_version', 'provenance.instrumentation.version', 'native'],
  ['sdk_name', 'provenance.instrumentation.sdkName', 'native'],
  ['sdk_version', 'provenance.instrumentation.sdkVersion', 'native'],
  ['trace_revision', 'provenance.conventions.coreTraceRevision', 'native'],
  ['http_revision_state', 'provenance.conventions.http.state', 'native'],
  ['http_revision_reason', 'provenance.conventions.http.reason', 'native'],
  ['http_revision_value', 'provenance.conventions.http.value', 'native'],
  ['genai_revision_state', 'provenance.conventions.genai.state', 'native'],
  ['genai_revision_reason', 'provenance.conventions.genai.reason', 'native'],
  ['mcp_revision_state', 'provenance.conventions.mcp.state', 'native'],
  ['mcp_revision_reason', 'provenance.conventions.mcp.reason', 'native'],
  ['sampling_state', 'coverage.sampling.state', 'native'],
  ['sampling_reason', 'coverage.sampling.reason', 'native'],
  ['sampling_mode', 'coverage.sampling.value.mode', 'native'],
  ['sampling_rate', 'coverage.sampling.value.rate', 'native'],
  ['sampled_state', 'coverage.sampled.state', 'native'],
  ['sampled_reason', 'coverage.sampled.reason', 'native'],
  ['sampled_value', 'coverage.sampled.value', 'native'],
  ['dropped_attributes_state', 'coverage.droppedAttributes.state', 'native'],
  ['dropped_attributes_reason', 'coverage.droppedAttributes.reason', 'native'],
  ['dropped_attributes_value', 'coverage.droppedAttributes.value', 'native'],
  ['dropped_events_state', 'coverage.droppedEvents.state', 'native'],
  ['dropped_events_reason', 'coverage.droppedEvents.reason', 'native'],
  ['dropped_events_value', 'coverage.droppedEvents.value', 'native'],
  ['dropped_links_state', 'coverage.droppedLinks.state', 'native'],
  ['dropped_links_reason', 'coverage.droppedLinks.reason', 'native'],
  ['dropped_links_value', 'coverage.droppedLinks.value', 'native'],
  ['collection_scope', 'coverage.collectionScope', 'native'],
  ['limitations', 'coverage.limitations', 'native'],
  ['transport_state', 'transport.state', 'native'],
  ['transport_reason', 'transport.reason', 'native'],
  ['transport_value', 'transport.value', 'native'],
  ['tool_reference_state', 'toolReference.state', 'native'],
  ['tool_reference_reason', 'toolReference.reason', 'native'],
  ['tool_reference_value', 'toolReference.value', 'native'],
  ['protocol_result_state', 'protocolResult.state', 'native'],
  ['protocol_result_reason', 'protocolResult.reason', 'native'],
  ['protocol_result_value', 'protocolResult.value', 'native'],
  ['protocol_state', 'protocol.state', 'native'],
  ['protocol_reason', 'protocol.reason', 'native'],
  ['protocol_value', 'protocol.value', 'native'],
  ['http_method_state', 'httpMethod.state', 'native'],
  ['http_method_reason', 'httpMethod.reason', 'native'],
  ['http_method_value', 'httpMethod.value', 'native'],
  ['http_status_state', 'httpStatusCode.state', 'native'],
  ['http_status_reason', 'httpStatusCode.reason', 'native'],
  ['http_status_value', 'httpStatusCode.value', 'native'],
] as const;

export function runtimeToRow(value: unknown): Record<string, unknown> {
  const row: Record<string, unknown> = {};
  for (const [column, path, encoding] of runtimeColumns) {
    let leaf: unknown = value;
    for (const key of path.split('.')) leaf = leaf && typeof leaf === 'object' ? (leaf as Record<string, unknown>)[key] : undefined;
    if (encoding === 'instant' && typeof leaf === 'string' && leaf.startsWith('0000-')) {
      leaf = '0001-' + leaf.slice(5, -1) + '+00 BC';
    }
    row[column] = leaf ?? null;
  }
  return row;
}

export function runtimeFromRow(row: Record<string, unknown>): unknown {
  if (!row || typeof row !== 'object' || typeof row.recorded_at !== 'string') throw new Error('RUNTIME_READBACK_INVALID');
  const result: Record<string, unknown> = {};
  for (const [column, path, encoding] of runtimeColumns) {
    let value = row[column];
    if (value === null || value === undefined) continue;
    if (encoding === 'decimal' && typeof value !== 'string') throw new Error('RUNTIME_READBACK_INVALID');
    if (encoding === 'instant') value = new Date(value as string).toISOString();
    const keys = path.split('.'); let node = result;
    for (const key of keys.slice(0, -1)) { node[key] ??= {}; node = node[key] as Record<string, unknown>; }
    node[keys[keys.length - 1]] = value;
  }
  result.recordedAt = { state: 'KNOWN', value: new Date(row.recorded_at as string).toISOString() };
  return result;
}
