import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { createClient } from '@supabase/supabase-js';
import { auditPostgresClient, type AuditSql } from '../helpers/audit-postgres-client';
import { fullChainCluster } from '../helpers/m16-definer-surface-fixtures';

const lit = (value: string) => `'${value.replace(/'/g, "''")}'`;
// Expected patterns are hand-written PostgreSQL ARE literals, not generated by the encoder.
const cases: ReadonlyArray<readonly [string, string, string]> = [
  ['C:\\temp', 'C:temp', String.raw`C:\\temp`],
  ['a\\b', 'ab', String.raw`a\\b`],
  ['trail\\', 'trail%', String.raw`trail\\`],
  ['\\', '%', String.raw`\\`],
  ['path\\%x', 'path%x', String.raw`path\\%x`],
  ['50%', '500', '50%'],
  ['a_b', 'acb', 'a_b'],
  ['x*y', 'xZZy', String.raw`x\*y`],
  ['a.b', 'acb', String.raw`a\.b`],
  ['a+b', 'aaab', String.raw`a\+b`],
  ['a?b', 'b', String.raw`a\?b`],
  ['a^b', 'ab', String.raw`a\^b`],
  ['a$b', 'ab', String.raw`a\$b`],
  ['a[b]', 'ab', String.raw`a\[b\]`],
  ['a{b}', 'ab', String.raw`a\{b\}`],
  ['a|b', 'a', String.raw`a\|b`],
  ['(policy)', 'policy', String.raw`\(policy\)`],
  ['risk)', 'risk', String.raw`risk\)`],
  ['(risk', 'risk', String.raw`\(risk`],
  ['alpha,beta', 'alpha', 'alpha,beta'],
  ['alpha,beta(policy)', 'alpha,beta', String.raw`alpha,beta\(policy\)`],
  ['quote"value', 'quotevalue', 'quote"value'],
  ['key:value', 'keyvalue', 'key:value'],
  ['quote"\\value', 'quote"value', String.raw`quote"\\value`],
  ['nEeDlE', 'need other', 'nEeDlE'],
  ['ordinary substring', 'ordinary other substring', 'ordinary substring'],
  ['x",event_type.ilike.%,event_description.ilike."y', 'unrelated', String.raw`x",event_type\.ilike\.%,event_description\.ilike\."y`],
  ['a{2}', 'aa', String.raw`a\{2\}`],
  ['(?i)a', 'a', String.raw`\(\?i\)a`],
  ['line\nbreak', 'line break', 'line\nbreak'],
];

test('M16 S1B.2R6 literal search through PostgREST decoding and real PG17', { timeout: 900_000 }, async t => {
  const pg = await fullChainCluster(message => t.diagnostic(message), { r3: true });
  t.after(() => pg.stop());
  Object.assign(process.env, { SUPABASE_URL: 'http://127.0.0.1:9', SUPABASE_ANON_KEY: 'r6-anon', SUPABASE_SERVICE_ROLE_KEY: 'r6-service' });
  const { db } = await import('../../lib/db');
  const queries: string[] = [];
  const sql: AuditSql = (query, role) => { queries.push(query); return pg.sql(query, role); };
  // Exercise the installed Supabase URL encoder too. Fetch is simulated locally;
  // only the audit GET subset is decoded and forwarded to the independent PG transport.
  const client = createClient('http://127.0.0.1:9', 'r6-service', {
    db: { schema: 'gov_repo' }, auth: { persistSession: false, autoRefreshToken: false },
    global: { fetch: async (input, init) => {
      const url = new URL(String(input));
      assert.equal(url.origin, 'http://127.0.0.1:9');
      assert.equal(url.pathname, '/rest/v1/governance_ledger');
      assert.equal(new Headers(init?.headers).get('accept-profile'), 'gov_repo');
      const params = url.searchParams;
      assert.deepEqual([...params.keys()].sort(), ['limit', 'offset', 'or', 'order', 'organisation_id', 'select']);
      assert.equal(params.get('select'), '*');
      assert.equal(params.get('order'), 'entry_sequence.desc');
      assert.match(params.get('organisation_id')!, /^eq\.[0-9a-f-]{36}$/);
      const expression = params.get('or')!;
      assert.ok(expression.startsWith('(') && expression.endsWith(')'));
      const offset = Number(params.get('offset')), limit = Number(params.get('limit'));
      const result: any = await auditPostgresClient(sql, 'service_role').from('governance_ledger')
        .select('*', { count: 'exact' }).eq('organisation_id', params.get('organisation_id')!.slice(3))
        .or(expression.slice(1, -1)).order('entry_sequence', { ascending: false }).range(offset, offset + limit - 1);
      assert.equal(result.error, null);
      return new Response(JSON.stringify(result.data), { status: 200, headers: {
        'content-type': 'application/json', 'content-range': `0-${result.data.length - 1}/${result.count}`,
      } });
    } },
  });
  Object.assign(db, { read: auditPostgresClient(sql, 'anon'), write: client });
  const { getEvents } = await import('../../repositories/audit');
  const actor = randomUUID();
  const append = async (tenant: string, type: string, description: string) => Number(await pg.svc(
    `select gov_repo.ledger_append(${lit(type)},${lit(description)},'S',gen_random_uuid(),${lit(actor)},null,${lit(tenant)},'{}')`,
  ));

  await t.test('transport passes raw regex to PG and aliases stars only for ILIKE', async () => {
    const tenant = randomUUID();
    await append(tenant, 'CONTROL', 'prefix acb suffix');
    const lookup = async (expression: string) => {
      const result: any = await auditPostgresClient(sql, 'service_role').from('governance_ledger')
        .select('*').eq('organisation_id', tenant).or(expression);
      assert.equal(result.error, null);
      return result.data.length;
    };
    assert.equal(await lookup('event_description.imatch."a.b"'), 1);
    assert.equal(await lookup(String.raw`event_description.imatch."a\\.b"`), 0);
    assert.equal(await lookup('event_description.ilike."*a*b*"'), 1);
    assert.equal(await lookup(String.raw`event_description.imatch."a\\*b"`), 0);
    assert.equal(await pg.svc('show standard_conforming_strings'), 'on');
  });

  for (const [search, control, decoded] of cases) await t.test(`literal ${JSON.stringify(search)}: exact matches, negative control, foreign tenant`, async () => {
    const tenant = randomUUID(), foreign = randomUUID();
    const expected = [
      await append(tenant, 'DESCRIPTION_MATCH', `prefix ${search} suffix`),
      await append(tenant, `prefix ${search.toUpperCase()} suffix`, 'type-only'),
    ].reverse();
    await append(tenant, `prefix ${control} suffix`, `prefix ${control} suffix`);
    await append(foreign, `prefix ${search} suffix`, `prefix ${search} suffix`);
    queries.length = 0;
    const result = await getEvents(tenant, { search });
    t.diagnostic(`search=${JSON.stringify(search)} control=${JSON.stringify(control)} total=${result.total}; SQL=${queries[0]}`);
    assert.equal(result.total, 2);
    assert.deepEqual(result.events.map(row => row.entry_sequence), expected);
    assert.ok(result.events.every(row => row.organisation_id === tenant));
    // Layer A has decoded the PostgREST value; layer B is interpreted by PG17, never JS RegExp.
    assert.ok(queries[0].includes(`event_description ~* ${lit(decoded)}`));
    assert.ok(queries[0].includes(`event_type ~* ${lit(decoded)}`));
  });
});
