create policy "Service role has full access to agents" on gov_repo.agents for all to service_role using(true) with check(true);
create policy "Org-scoped access to agents" on gov_repo.agents for select to authenticated using(organisation_id=(select organisation_id from gov_repo.governance_users where email=auth.email() limit 1));
create table gov_repo.agent_edges (
 edge_id uuid primary key default uuid_generate_v4(), source_agent_id uuid not null references gov_repo.agents(agent_id), target_agent_id uuid not null references gov_repo.agents(agent_id), relationship_type gov_repo.edge_relationship not null, direction varchar(20) not null default 'unidirectional' check(direction in ('unidirectional','bidirectional')), weight numeric(4,3) not null default 0.5 check(weight between 0.001 and 1.000), requires_approval boolean not null default false, approval_mode varchar(30) not null default 'automatic' check(approval_mode in ('automatic','human_review','human_approval')), approved_by uuid references gov_repo.governance_users(user_id), approved_at timestamptz, sla_ms integer, max_calls_per_minute integer, timeout_ms integer, is_active boolean not null default true, deactivated_reason text, deactivated_at timestamptz, data_classification gov_repo.classification_level not null default 'internal', carries_pii boolean not null default false, carries_phi boolean not null default false, carries_financial boolean not null default false, metadata jsonb not null default '{}', organisation_id uuid not null references gov_repo.organisations(organisation_id), ledger_entry_seq bigint references gov_repo.governance_ledger(entry_sequence), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint agent_edges_no_self_loop check(source_agent_id<>target_agent_id), constraint agent_edges_unique unique(source_agent_id,target_agent_id,relationship_type));
comment on table gov_repo.agent_edges is 'Directed edges of the Agent Knowledge Graph. CG-AG-011: all agent-to-agent relationships MUST be registered here before production. weight: 1.0 = critical (full risk propagation), 0.1 = loose coupling. carries_pii/phi/financial: triggers mandatory CG-AG-009 Data Governance review.';
create index idx_agent_edges_source on gov_repo.agent_edges(source_agent_id) where is_active=true;
create index idx_agent_edges_target on gov_repo.agent_edges(target_agent_id) where is_active=true;
create index idx_agent_edges_type on gov_repo.agent_edges(relationship_type);
create index idx_agent_edges_org on gov_repo.agent_edges(organisation_id);
create index idx_agent_edges_pii on gov_repo.agent_edges(carries_pii) where carries_pii=true;
create index idx_agent_edges_traversal on gov_repo.agent_edges(source_agent_id,target_agent_id,is_active,weight desc);
create trigger trg_agent_edges_updated_at before update on gov_repo.agent_edges for each row execute function gov_repo.set_updated_at();
alter table gov_repo.agent_edges enable row level security;
create policy "Service role has full access to agent_edges" on gov_repo.agent_edges for all to service_role using(true) with check(true);
create policy "Org-scoped access to agent_edges" on gov_repo.agent_edges for select to authenticated using(organisation_id=(select organisation_id from gov_repo.governance_users where email=auth.email() limit 1));
create table gov_repo.agent_resource_links (
 link_id uuid primary key default uuid_generate_v4(), agent_id uuid not null references gov_repo.agents(agent_id), resource_type gov_repo.resource_type not null, resource_ref varchar(255) not null, resource_name varchar(255) not null, resource_version varchar(50), resource_provider varchar(255), resource_endpoint text, access_type gov_repo.access_type not null, is_active boolean not null default true, requires_approval boolean not null default false, data_classification gov_repo.classification_level not null default 'internal', processes_pii boolean not null default false, processes_phi boolean not null default false, processes_financial boolean not null default false, data_residency varchar(50), cg_ag_004_compliant boolean not null default false, cg_ag_005_compliant boolean not null default false, cg_ag_006_compliant boolean not null default false, cg_ag_009_compliant boolean not null default false, last_reviewed_at timestamptz, reviewed_by uuid references gov_repo.governance_users(user_id), next_review_date date, metadata jsonb not null default '{}', organisation_id uuid not null references gov_repo.organisations(organisation_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint agent_resource_links_unique unique(agent_id,resource_type,resource_ref));
comment on table gov_repo.agent_resource_links is 'Links agents to all external resources: MCP, tools, models, prompts, databases. CG-AG-003|004|005|006|009. processes_pii/phi/financial: triggers enhanced governance and DPIA requirements. resource_provider links to gov_repo.third_party_providers (Migration 006).';
create index idx_agent_resource_agent on gov_repo.agent_resource_links(agent_id);
create index idx_agent_resource_type on gov_repo.agent_resource_links(resource_type);
create index idx_agent_resource_org on gov_repo.agent_resource_links(organisation_id);
create index idx_agent_resource_pii on gov_repo.agent_resource_links(processes_pii) where processes_pii=true;
create index idx_agent_resource_mcp on gov_repo.agent_resource_links(resource_type) where resource_type='mcp_server' and is_active=true;
create trigger trg_agent_resource_links_updated_at before update on gov_repo.agent_resource_links for each row execute function gov_repo.set_updated_at();
alter table gov_repo.agent_resource_links enable row level security;
create policy "Service role has full access to agent_resource_links" on gov_repo.agent_resource_links for all to service_role using(true) with check(true);
create policy "Org-scoped access to agent_resource_links" on gov_repo.agent_resource_links for select to authenticated using(organisation_id=(select organisation_id from gov_repo.governance_users where email=auth.email() limit 1));
create table gov_repo.agent_risk_propagation (
 propagation_id uuid primary key default uuid_generate_v4(), risk_source_agent_id uuid not null references gov_repo.agents(agent_id), affected_agent_id uuid not null references gov_repo.agents(agent_id), propagation_path uuid[] not null, propagation_depth integer not null generated always as (coalesce(array_length(propagation_path,1),0)) stored, propagation_type gov_repo.propagation_type not null default 'direct', impact_score numeric(5,4) not null check(impact_score between 0 and 1), criticality gov_repo.agent_risk_level not null default 'low', financial_impact_eur bigint, processes_impacted text[], agents_in_chain integer not null default 1, risk_id uuid references gov_repo.risk_entries(risk_id), is_active boolean not null default true, invalidated_reason text, computed_at timestamptz not null default now(), expires_at timestamptz, organisation_id uuid not null references gov_repo.organisations(organisation_id), constraint propagation_unique unique(risk_source_agent_id,affected_agent_id), constraint propagation_no_self check(risk_source_agent_id<>affected_agent_id));
create or replace function gov_repo.set_propagation_criticality() returns trigger language plpgsql as $$ begin new.criticality := case when new.impact_score>=0.75 then 'critical'::gov_repo.agent_risk_level when new.impact_score>=0.50 then 'high'::gov_repo.agent_risk_level when new.impact_score>=0.25 then 'medium'::gov_repo.agent_risk_level else 'low'::gov_repo.agent_risk_level end; return new; end; $$;
create trigger trg_propagation_criticality before insert or update of impact_score on gov_repo.agent_risk_propagation for each row execute function gov_repo.set_propagation_criticality();
comment on table gov_repo.agent_risk_propagation is 'Pre-computed risk propagation paths across the agent graph. Answers: "If FinanceAgent fails, which agents are impacted and at what cost?" impact_score = source_risk_score × product of edge weights along path. criticality is auto-derived by trigger trg_propagation_criticality [FIX-1]. financial_impact_eur enables CFO/CISO Risk Officer Lens. Recomputed by gov_repo.recompute_risk_propagation() on graph changes.';
create index idx_risk_prop_source on gov_repo.agent_risk_propagation(risk_source_agent_id);
create index idx_risk_prop_affected on gov_repo.agent_risk_propagation(affected_agent_id);
create index idx_risk_prop_criticality on gov_repo.agent_risk_propagation(criticality) where is_active=true;
create index idx_risk_prop_org on gov_repo.agent_risk_propagation(organisation_id);
create index idx_risk_prop_score on gov_repo.agent_risk_propagation(impact_score desc) where is_active=true;;
