create table gov_repo.conformity_assessments (
  assessment_id uuid primary key default uuid_generate_v4(), assessment_code varchar(20) not null, agent_id uuid not null, assessment_type gov_repo.conformity_type not null default 'internal', ai_act_annex_ref varchar(100), status gov_repo.conformity_status not null default 'not_started', scope_description text not null, methodology text not null, assessor_id uuid references gov_repo.governance_users(user_id), assessor_org varchar(255), start_date date not null, completion_date date, valid_until date, outcome gov_repo.conformity_outcome, non_conformities jsonb default '[]', conditions text, eu_ai_db_ref varchar(100), declaration_evidence_id uuid references gov_repo.evidence(evidence_id), technical_file_evidence_id uuid references gov_repo.evidence(evidence_id), organisation_id uuid not null references gov_repo.organisations(organisation_id), ledger_entry_seq bigint references gov_repo.governance_ledger(entry_sequence), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint conformity_code_org_unique unique(assessment_code,organisation_id));
comment on table gov_repo.conformity_assessments is 'EU AI Act Article 43 conformity assessments for high-risk AI agents. Automatically triggered when CG-AG-010 classifies an agent as high-risk. outcome must be set before registration in EU AI Database (eu_ai_db_ref).';
comment on column gov_repo.conformity_assessments.non_conformities is 'JSON array of non-conformity objects: [{id, description, severity, article_ref, remediation}]';
create index idx_conformity_org on gov_repo.conformity_assessments(organisation_id);
create index idx_conformity_agent on gov_repo.conformity_assessments(agent_id);
create index idx_conformity_status on gov_repo.conformity_assessments(status);
create trigger trg_conformity_updated_at before update on gov_repo.conformity_assessments for each row execute function gov_repo.set_updated_at();
alter table gov_repo.conformity_assessments enable row level security;
create policy "Service role has full access to conformity_assessments" on gov_repo.conformity_assessments for all to service_role using(true) with check(true);
create policy "Org-scoped access to conformity_assessments" on gov_repo.conformity_assessments for select to authenticated using(organisation_id=(select organisation_id from gov_repo.governance_users where email=auth.email() limit 1));
create table gov_repo.control_assessments (
  assessment_id uuid primary key default uuid_generate_v4(), control_ref varchar(12) not null, agent_id uuid, period_start date not null, period_end date not null, assessor_id uuid not null references gov_repo.governance_users(user_id), reviewer_id uuid references gov_repo.governance_users(user_id), status gov_repo.assessment_status not null default 'planned', maturity_level smallint check(maturity_level between 0 and 5), operating_effectiveness gov_repo.operating_effectiveness, design_effectiveness gov_repo.design_effectiveness, findings_summary jsonb not null default '[]', evidence_ids uuid[] not null default '{}', remediation_ids uuid[] not null default '{}', overall_conclusion text, next_assessment_date date, organisation_id uuid not null references gov_repo.organisations(organisation_id), ledger_entry_seq bigint references gov_repo.governance_ledger(entry_sequence), created_at timestamptz not null default now(), completed_at timestamptz, updated_at timestamptz not null default now(), constraint control_ref_format check(control_ref ~ '^CG-AG-0(0[1-9]|1[0-2])$'), constraint period_order check(period_end >= period_start));
comment on table gov_repo.control_assessments is 'Periodic operating effectiveness assessments of CG-AGF controls (CG-AG-001..012). maturity_level: 0=Absent | 1=Initial | 2=Managed | 3=Defined | 4=Quantitative | 5=Optimising. NULL agent_id = organisation-level control assessment (not agent-specific).';
create index idx_control_assessments_org on gov_repo.control_assessments(organisation_id);
create index idx_control_assessments_control on gov_repo.control_assessments(control_ref);
create index idx_control_assessments_agent on gov_repo.control_assessments(agent_id) where agent_id is not null;
create index idx_control_assessments_status on gov_repo.control_assessments(status);
create index idx_control_assessments_maturity on gov_repo.control_assessments(maturity_level);
create trigger trg_control_assessments_updated_at before update on gov_repo.control_assessments for each row execute function gov_repo.set_updated_at();
alter table gov_repo.control_assessments enable row level security;
create policy "Service role has full access to control_assessments" on gov_repo.control_assessments for all to service_role using(true) with check(true);
create policy "Org-scoped access to control_assessments" on gov_repo.control_assessments for select to authenticated using(organisation_id=(select organisation_id from gov_repo.governance_users where email=auth.email() limit 1));
create table gov_repo.control_findings (
  finding_id uuid primary key default uuid_generate_v4(), finding_code varchar(20) not null, assessment_id uuid not null references gov_repo.control_assessments(assessment_id) on delete cascade, control_ref varchar(12) not null, finding_type gov_repo.finding_type not null, severity gov_repo.finding_severity not null, title varchar(255) not null, description text not null, root_cause text, impact text not null, recommendation text not null, management_response text, status gov_repo.finding_status not null default 'open', target_date date not null, owner_id uuid not null references gov_repo.governance_users(user_id), evidence_ids uuid[] not null default '{}', created_at timestamptz not null default now(), closed_at timestamptz, updated_at timestamptz not null default now());
create index idx_control_findings_assessment on gov_repo.control_findings(assessment_id);
create index idx_control_findings_control on gov_repo.control_findings(control_ref);
create index idx_control_findings_severity on gov_repo.control_findings(severity);
create index idx_control_findings_status on gov_repo.control_findings(status) where status <> 'closed';
create trigger trg_control_findings_updated_at before update on gov_repo.control_findings for each row execute function gov_repo.set_updated_at();
alter table gov_repo.control_findings enable row level security;
create policy "Service role has full access to control_findings" on gov_repo.control_findings for all to service_role using(true) with check(true);
create policy "Org-scoped access to control_findings via assessment" on gov_repo.control_findings for select to authenticated using(assessment_id in (select assessment_id from gov_repo.control_assessments where organisation_id=(select organisation_id from gov_repo.governance_users where email=auth.email() limit 1)));
create or replace view gov_repo.v_active_exceptions as select e.exception_id,e.exception_code,e.title,e.exception_type,e.control_ref,e.agent_id,e.valid_from,e.valid_until,e.valid_until-current_date as days_remaining,e.review_frequency,e.next_review_date,e.valid_until-current_date <= 30 as expiring_soon,e.valid_until < current_date as is_overdue,u.full_name as requested_by_name,a.full_name as approved_by_name,e.organisation_id from gov_repo.exceptions e join gov_repo.governance_users u on u.user_id=e.requested_by left join gov_repo.governance_users a on a.user_id=e.approved_by where e.status='active';
comment on view gov_repo.v_active_exceptions is 'Active exceptions with expiry countdown. expiring_soon = expires within 30 days.';
create or replace view gov_repo.v_pending_approvals as select d.decision_id,d.request_id,r.request_code,r.title,r.subject_type,r.subject_id,r.priority,d.workflow_step,d.step_name,d.assigned_to as assigned_user_id,u.full_name as assigned_user_name,u.email as assigned_user_email,d.deadline,d.deadline < now() as is_overdue,d.deadline-now() as time_remaining,r.organisation_id from gov_repo.approval_decisions d join gov_repo.approval_requests r on r.request_id=d.request_id join gov_repo.governance_users u on u.user_id=d.assigned_to where d.decided_at is null and r.status in ('submitted','in_review','escalated');
comment on view gov_repo.v_pending_approvals is 'All unresolved approval steps with assignee and SLA status. is_overdue = deadline passed.';;
