create or replace function gov_repo.ai_system_evidence_report(p_system_id uuid)
returns table(evidence_category text,evidence_id uuid,evidence_code varchar,title varchar,evidence_type gov_repo.evidence_type,status gov_repo.evidence_status,verified_at timestamptz,retention_until date,classification gov_repo.classification_level,collected_at timestamptz,eu_ai_act_article text,is_mandatory boolean)
language sql security definer as $$
select 'Technical Documentation (Art. 11 + Annex IV)'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 11 + Annex IV'::text,true from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.technical_doc_evidence_id where s.system_id=p_system_id and s.technical_doc_evidence_id is not null
union all select 'Declaration of Conformity (Art. 47)'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 47(2)'::text,(s.risk_class='high') from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.declaration_of_conformity_id where s.system_id=p_system_id and s.declaration_of_conformity_id is not null
union all select 'Risk Management System (Art. 9)'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 9'::text,(s.risk_class='high') from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.risk_mgmt_evidence_id where s.system_id=p_system_id and s.risk_mgmt_evidence_id is not null
union all select 'Post-Market Surveillance Plan (Art. 72)'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 72'::text,(s.risk_class='high') from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.pms_plan_evidence_id where s.system_id=p_system_id and s.pms_plan_evidence_id is not null
union all select 'Fundamental Rights Impact Assessment (Art. 9(9))'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 9(9)'::text,(s.risk_class='high') from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.fria_evidence_id where s.system_id=p_system_id and s.fria_evidence_id is not null
union all select 'Bias & Fairness Assessment (Art. 9(7))'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 9(7)'::text,false from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.bias_assessment_evidence_id where s.system_id=p_system_id and s.bias_assessment_evidence_id is not null
union all select 'Adversarial Testing — GPAI Systemic Risk (Art. 55)'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 55(1)(a)'::text,(s.gpai_tier='gpai_systemic_risk') from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.adversarial_testing_evidence_id where s.system_id=p_system_id and s.adversarial_testing_evidence_id is not null
union all select 'Annex III Exception Justification (Art. 6(3))'::text,e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.verified_at,e.retention_until,e.classification,e.collected_at,'Art. 6(3)'::text,s.annex_iii_exception_claimed from gov_repo.ai_systems s join gov_repo.evidence e on e.evidence_id=s.annex_iii_exception_evidence_id where s.system_id=p_system_id and s.annex_iii_exception_evidence_id is not null
order by 12 desc,1; $$;
insert into gov_repo.mandates(mandate_code,regulation,section_ref,title,requirement_text,requirement_type,effective_date,applicability,mapped_controls) values
('EU-AI-ACT-ART-6','EU AI Act (2024/1689)','Art. 6 + Annex III','Classification Rules for High-Risk AI Systems','AI systems listed in Annex III and AI systems embedded in regulated products shall be considered high-risk. Providers may claim exception under Art. 6(3) if they demonstrate no significant risk of harm.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["provider"]}',array['CG-AG-010']),
('EU-AI-ACT-ART-13','EU AI Act (2024/1689)','Art. 13','Transparency and Provision of Information to Deployers','High-risk AI systems shall be sufficiently transparent to enable deployers to interpret output and use it appropriately.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["provider"]}',array['CG-AG-007']),
('EU-AI-ACT-ART-17','EU AI Act (2024/1689)','Art. 17','Quality Management System','Providers of high-risk AI systems shall implement a quality management system covering the lifecycle.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["provider"]}',array['CG-AG-001','CG-AG-010']),
('EU-AI-ACT-ART-43','EU AI Act (2024/1689)','Art. 43','Conformity Assessment','Before placing a high-risk AI system on the market, providers shall carry out a conformity assessment.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["provider"]}',array['CG-AG-010']),
('EU-AI-ACT-ART-47','EU AI Act (2024/1689)','Art. 47','EU Declaration of Conformity and CE Marking','Providers shall draw up an EU Declaration of Conformity and affix CE marking to high-risk AI systems before market placement.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["provider"]}',array['CG-AG-010']),
('EU-AI-ACT-ART-49','EU AI Act (2024/1689)','Art. 49','Registration in EU AI Database','Providers shall register high-risk systems in the EU AI database before market placement or service.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["provider","deployer"]}',array['CG-AG-001','CG-AG-010']),
('EU-AI-ACT-ART-53','EU AI Act (2024/1689)','Art. 53','GPAI Model Obligations','Providers of GPAI models shall maintain technical documentation, downstream information, copyright compliance and training-content summary.','mandatory','2025-08-02','{"sectors":["all"],"gpai":true,"roles":["provider"]}',array['CG-AG-003']),
('EU-AI-ACT-ART-55','EU AI Act (2024/1689)','Art. 55','GPAI Models with Systemic Risk — Additional Obligations','Providers of systemic-risk GPAI models shall perform adversarial testing, incident reporting and cybersecurity measures.','mandatory','2025-08-02','{"sectors":["all"],"gpai_systemic_risk":true,"roles":["provider"]}',array['CG-AG-003','CG-AG-010']),
('EU-AI-ACT-ART-72','EU AI Act (2024/1689)','Art. 72','Post-Market Surveillance','Providers of high-risk AI systems shall establish and document post-market surveillance.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["provider"]}',array['CG-AG-010','CG-AG-012']),
('EU-AI-ACT-ART-26','EU AI Act (2024/1689)','Art. 26','Obligations of Deployers of High-Risk AI Systems','Deployers shall implement oversight, governance, logs and impact assessment obligations.','mandatory','2025-08-02','{"sectors":["all"],"risk_classes":["high"],"roles":["deployer","provider_and_deployer"]}',array['CG-AG-007','CG-AG-008','CG-AG-009']),
('ISO42001-8-3','ISO/IEC 42001:2023','Clause 8.3','AI System Impact Assessment','The organisation shall conduct impact assessments for AI systems and implement mitigation measures.','mandatory','2023-12-18','{"sectors":["all"]}',array['CG-AG-009','CG-AG-010']),
('NIST-MANAGE-1-3','NIST AI RMF 1.0','MANAGE 1.3','Risk Tolerance and Residual Risk','Responses to AI risks are prioritized and documented based on risk tolerance; residual risks are accepted or escalated with rationale.','recommended','2023-01-26','{"sectors":["all"]}',array['CG-AG-010','CG-AG-012']) on conflict(mandate_code) do nothing;;
