create table gov_repo.mandates (
  mandate_id uuid primary key default uuid_generate_v4(), mandate_code varchar(50) not null, regulation varchar(100) not null, section_ref varchar(100) not null, title varchar(255) not null, requirement_text text not null, requirement_type gov_repo.mandate_type not null default 'mandatory', effective_date date not null, applicability jsonb not null default '{}', mapped_controls varchar(12)[] not null default '{}', mapped_policies uuid[] not null default '{}', organisation_id uuid references gov_repo.organisations (organisation_id), compliance_status gov_repo.compliance_status not null default 'not_assessed', last_assessed date, created_at timestamptz not null default now(), constraint mandates_code_unique unique (mandate_code));
comment on table gov_repo.mandates is 'Regulatory mandate catalogue. Maps regulation articles to CG-AGF controls and internal policies. NULL organisation_id = system-wide mandate applicable to all tenants.';
comment on column gov_repo.mandates.mapped_controls is 'CG-AGF control references (CG-AG-001 through CG-AG-012) that satisfy this mandate.';
insert into gov_repo.mandates (mandate_code, regulation, section_ref, title, requirement_text, mapped_controls, effective_date) values
('EU-AI-ACT-ART-9','EU_AI_ACT','Article 9','Risk Management System','High-risk AI systems shall have a risk management system established, implemented, documented and maintained throughout the entire lifecycle.',array['CG-AG-010','CG-AG-012'],'2025-08-01'),
('EU-AI-ACT-ART-10','EU_AI_ACT','Article 10','Data and Data Governance','High-risk AI systems which make use of techniques involving the training of models with data shall be developed on the basis of training, validation and testing data sets that meet quality criteria.',array['CG-AG-003','CG-AG-009'],'2025-08-01'),
('EU-AI-ACT-ART-11','EU_AI_ACT','Article 11 + Annex IV','Technical Documentation','Providers of high-risk AI systems shall draw up technical documentation before that system is placed on the market or put into service.',array['CG-AG-001','CG-AG-003'],'2025-08-01'),
('EU-AI-ACT-ART-12','EU_AI_ACT','Article 12','Record Keeping / Automatic Logging','High-risk AI systems shall technically allow for the automatic recording of events throughout the lifetime of the system.',array['CG-AG-008'],'2025-08-01'),
('EU-AI-ACT-ART-13','EU_AI_ACT','Article 13','Transparency and Provision of Information','High-risk AI systems shall be designed and developed in such a way as to ensure that their operation is sufficiently transparent to enable deployers to interpret the system''s output.',array['CG-AG-007'],'2025-08-01'),
('EU-AI-ACT-ART-14','EU_AI_ACT','Article 14','Human Oversight','High-risk AI systems shall be designed and developed with human oversight measures, including the ability to interrupt, override or stop the system.',array['CG-AG-007'],'2025-08-01'),
('EU-AI-ACT-ART-15','EU_AI_ACT','Article 15','Accuracy, Robustness and Cybersecurity','High-risk AI systems shall be designed and developed in such a way that they achieve, in the light of their intended purpose, an appropriate level of accuracy, robustness, and cybersecurity.',array['CG-AG-003','CG-AG-005'],'2025-08-01'),
('DORA-ART-5','DORA','Article 5','ICT Risk Management Framework','Financial entities shall have in place a comprehensive, documented and annually reviewed ICT risk management framework.',array['CG-AG-001','CG-AG-002','CG-AG-010'],'2025-01-17'),
('DORA-ART-8','DORA','Article 8','ICT Asset Management','Financial entities shall identify and classify ICT assets, including AI systems and models, based on their criticality.',array['CG-AG-001','CG-AG-003','CG-AG-010'],'2025-01-17'),
('DORA-ART-9','DORA','Article 9','ICT Security Policies','Financial entities shall develop, document and implement an information security policy addressing access control, cryptography, supply chain risk and audit logging.',array['CG-AG-004','CG-AG-005','CG-AG-006','CG-AG-009'],'2025-01-17'),
('DORA-ART-10','DORA','Article 10','ICT Logging and Monitoring','Financial entities shall have logging and monitoring processes in place to enable detection of anomalous activities and ICT-related incidents.',array['CG-AG-008'],'2025-01-17'),
('DORA-ART-28','DORA','Article 28','ICT Third-Party Risk Management','Financial entities shall manage ICT third-party risk including AI model providers, MCP servers and cloud services.',array['CG-AG-003','CG-AG-006'],'2025-01-17'),
('ISO42001-6-1','ISO_42001','§6.1','Actions to Address Risks and Opportunities','The organisation shall determine risks and opportunities related to its AI systems and plan actions to address them.',array['CG-AG-010'],'2023-12-01'),
('ISO42001-8-4','ISO_42001','§8.4','AI System Impact Assessment','The organisation shall carry out AI system impact assessments throughout the AI system lifecycle.',array['CG-AG-010','CG-AG-003'],'2023-12-01'),
('NIST-GOVERN-1-2','NIST_AI_RMF','GOVERN 1.2','Accountability Structures','Accountability structures are in place so that appropriate teams and individuals are empowered, responsible, and trained for mapping, measuring, and managing AI risks.',array['CG-AG-002','CG-AG-007'],'2023-01-26'),
('NIST-MAP-1-5','NIST_AI_RMF','MAP 1.5','AI System Context','Organisational risk tolerances are determined and documented. AI system context is established and understood.',array['CG-AG-001','CG-AG-010'],'2023-01-26'),
('GDPR-ART-22','GDPR','Article 22','Automated Individual Decision-Making','Data subjects shall have the right not to be subject to a decision based solely on automated processing, including profiling, which produces legal or similarly significant effects.',array['CG-AG-007','CG-AG-012'],'2018-05-25'),
('GDPR-ART-35','GDPR','Article 35','Data Protection Impact Assessment','Where processing is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall carry out an assessment of the impact of the envisaged processing operations.',array['CG-AG-009'],'2018-05-25');
alter table gov_repo.mandates enable row level security;
create policy "Service role has full access to mandates" on gov_repo.mandates for all to service_role using (true) with check (true);
create policy "Authenticated users can read mandates" on gov_repo.mandates for select to authenticated using (true);
create table gov_repo.governance_policies (
 policy_id uuid primary key default uuid_generate_v4(), policy_code varchar(20) not null, title varchar(255) not null, description text, policy_type gov_repo.policy_type not null, status gov_repo.policy_status not null default 'draft', effective_date date, expiry_date date, owner_user_id uuid not null references gov_repo.governance_users(user_id), approver_user_id uuid references gov_repo.governance_users(user_id), organisation_id uuid not null references gov_repo.organisations(organisation_id), parent_policy_id uuid references gov_repo.governance_policies(policy_id), current_version_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references gov_repo.governance_users(user_id), constraint governance_policies_code_org_unique unique(policy_code,organisation_id), constraint policy_expiry_after_effective check (expiry_date is null or expiry_date > effective_date));
comment on table gov_repo.governance_policies is 'AI governance policy master record. Content lives in policy_versions (versioned, immutable).';
comment on column gov_repo.governance_policies.current_version_id is 'Points to the currently active approved version. NULL until first version is approved.';
comment on column gov_repo.governance_policies.parent_policy_id is 'For hierarchical policies (e.g. sub-policy of an overarching AI Governance Policy).';
create index idx_gov_policies_org on gov_repo.governance_policies(organisation_id);
create index idx_gov_policies_status on gov_repo.governance_policies(status);
create index idx_gov_policies_owner on gov_repo.governance_policies(owner_user_id);
create trigger trg_governance_policies_updated_at before update on gov_repo.governance_policies for each row execute function gov_repo.set_updated_at();
alter table gov_repo.governance_policies enable row level security;
create policy "Service role has full access to governance_policies" on gov_repo.governance_policies for all to service_role using (true) with check (true);
create policy "Org-scoped access to governance_policies" on gov_repo.governance_policies for select to authenticated using (organisation_id=(select organisation_id from gov_repo.governance_users where email=auth.email() limit 1));
create table gov_repo.policy_versions (
 version_id uuid primary key default uuid_generate_v4(), policy_id uuid not null references gov_repo.governance_policies(policy_id) on delete cascade, version_number integer not null, version_label varchar(20) not null, content_markdown text not null, content_hash char(64) not null, change_summary text not null, status gov_repo.version_status not null default 'draft', reviewed_by uuid references gov_repo.governance_users(user_id), approved_by uuid references gov_repo.governance_users(user_id), approval_date timestamptz, qes_signature_id uuid references gov_repo.qes_signatures(signature_id), ledger_entry_seq bigint references gov_repo.governance_ledger(entry_sequence), created_at timestamptz not null default now(), created_by uuid not null references gov_repo.governance_users(user_id), constraint policy_versions_unique unique(policy_id,version_number), constraint policy_version_approval_consistent check ((approved_by is null)=(approval_date is null)));
comment on table gov_repo.policy_versions is 'Immutable versioned snapshots of policy content. Once approved, content cannot change. A new version must be created for any content modification.';;
