-- =============================================================================
-- CODEGUARD AI GOVERNANCE OS
-- Migration: Atomic Legacy Signup RPC
-- Purpose: Transactional signup that atomically creates:
--          1. Organisation (org_code generated BY THIS FUNCTION — see below)
--          2. Governance User
--          3. GOVERNANCE_ADMIN role assignment
--
-- FAIL CLOSED: Any failure rolls back the complete operation.
--              No orphan organisation. No orphan user.
--
-- SECURITY: SECURITY INVOKER (caller must be privileged - service_role)
--           Explicit search_path.
--           EXECUTE revoked from public/anon/authenticated.
--           EXECUTE granted ONLY to service_role.
--
-- ORG_CODE OWNERSHIP: org_code is a persisted organisation identity attribute.
-- Its generation is owned entirely by this function, inside the same Unit of
-- Work that creates the organisation — the caller supplies business signup
-- data only (email, password hash, names) and has no authority over
-- org_code. The suffix is derived from this function's own freshly
-- generated organisation_id (a cryptographically-random pg_catalog.gen_random_uuid()
-- value), so the database is the sole source of both identifiers. The
-- UNIQUE(org_code) constraint remains the final invariant: this is a
-- collision-resistance measure, not a probabilistic uniqueness guarantee.
--
-- ORGANISATION INDUSTRY PROFILE — OUT OF SCOPE FOR THIS RPC: canonical
-- gov_repo.organisations has no column for an industry/sector classification
-- (it never has; there is no external_refs or equivalent field on this
-- table). This RPC therefore does not accept or persist an industry value.
-- The caller (application layer) may still know and use an industry value
-- for its own immediate session/UX purposes — it is simply not part of the
-- canonical Auth persistence boundary. Persisting organisation industry
-- classification durably is an explicit, separate domain/data-model
-- decision outside this milestone.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Drop function if exists (clean idempotency)
-- -----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS gov_repo.signup_legacy(
  p_email varchar,
  p_password_hash varchar,
  p_full_name varchar,
  p_org_name varchar,
  p_org_code varchar,
  p_industry_profile varchar
);

DROP FUNCTION IF EXISTS gov_repo.signup_legacy(
  p_email varchar,
  p_password_hash varchar,
  p_full_name varchar,
  p_org_name varchar,
  p_industry_profile varchar
);

DROP FUNCTION IF EXISTS gov_repo.signup_legacy(
  p_email varchar,
  p_password_hash varchar,
  p_full_name varchar,
  p_org_name varchar
);

-- -----------------------------------------------------------------------------
-- Create the function
--
-- SECURITY INVOKER: The caller already uses service_role capability.
-- We do NOT use SECURITY DEFINER because:
--   1. Caller is already privileged
--   2. SECURITY DEFINER increases attack surface unnecessarily
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION gov_repo.signup_legacy(
  p_email varchar,
  p_password_hash varchar,
  p_full_name varchar,
  p_org_name varchar
)
RETURNS TABLE (
  user_id uuid,
  email varchar,
  full_name varchar,
  organisation_id uuid,
  organisation_name varchar,
  role_id uuid,
  role_code varchar
)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = 'gov_repo', 'pg_catalog'
AS $$
DECLARE
  v_org_id uuid;
  v_user_id uuid;
  v_admin_role_id uuid;
  v_admin_role_code varchar := 'GOVERNANCE_ADMIN';
  v_org_code_prefix varchar(8);
  v_org_code_suffix varchar(11);
  v_org_code varchar(20);
BEGIN
  -- ===========================================================================
  -- VALIDATION: Input preconditions
  -- ===========================================================================
  IF p_email IS NULL OR trim(p_email) = '' THEN
    RAISE EXCEPTION 'Email is required';
  END IF;

  IF p_password_hash IS NULL OR trim(p_password_hash) = '' THEN
    RAISE EXCEPTION 'Password hash is required';
  END IF;

  IF p_full_name IS NULL OR trim(p_full_name) = '' THEN
    RAISE EXCEPTION 'Full name is required';
  END IF;

  IF p_org_name IS NULL OR trim(p_org_name) = '' THEN
    RAISE EXCEPTION 'Organisation name is required';
  END IF;

  -- ===========================================================================
  -- ROLE LOOKUP: Resolve GOVERNANCE_ADMIN system role
  -- Must happen FIRST so we fail early if role is missing
  -- ===========================================================================
  SELECT gr.role_id, gr.role_code
  INTO v_admin_role_id, v_admin_role_code
  FROM gov_repo.governance_roles gr
  WHERE gr.role_code = v_admin_role_code
    AND gr.is_system_role = true
  LIMIT 1;

  IF v_admin_role_id IS NULL THEN
    RAISE EXCEPTION 'System role GOVERNANCE_ADMIN not found. Aborting signup.';
  END IF;

  -- ===========================================================================
  -- STEP 1: Create organisation
  --
  -- org_code generation (DATABASE-AUTHORITATIVE, single source of truth):
  --   1. Generate the organisation_id here, up front, so BOTH the primary
  --      key and the org_code suffix are derived from the same
  --      cryptographically-random pg_catalog.gen_random_uuid() value.
  --      (gen_random_uuid() is used instead of uuid_generate_v4() because it
  --      is a pg_catalog-native built-in on PostgreSQL 13+ and resolves
  --      correctly under this function's restricted
  --      SET search_path = 'gov_repo', 'pg_catalog' — uuid_generate_v4()
  --      lives in the uuid-ossp extension's schema, which is deliberately
  --      NOT on this search_path.)
  --   2. Prefix: readable, derived from p_org_name, uppercased, stripped to
  --      [A-Z0-9], truncated to 8 chars (falls back to 'ORG' if the name
  --      contains no alphanumeric characters).
  --   3. Suffix: first 11 hex characters of the generated organisation_id
  --      (44 bits of entropy) — materially stronger than a 32-bit/8-hex
  --      suffix (2^12 = 4096x the keyspace).
  --   4. prefix(<=8) + '_' + suffix(11) = <=20 chars, exactly the
  --      organisations.org_code varchar(20) limit.
  --   5. UNIQUE(org_code) is the final invariant. This function makes NO
  --      probabilistic uniqueness claim: on the astronomically unlikely
  --      event of a collision, the INSERT below raises and this entire
  --      transaction (organisation + user) rolls back atomically — no
  --      orphan state, no retry loop.
  -- ===========================================================================
  v_org_id := pg_catalog.gen_random_uuid();

  v_org_code_prefix := NULLIF(
    substr(regexp_replace(upper(p_org_name), '[^A-Z0-9]', '', 'g'), 1, 8),
    ''
  );
  IF v_org_code_prefix IS NULL THEN
    v_org_code_prefix := 'ORG';
  END IF;

  v_org_code_suffix := upper(substr(replace(v_org_id::text, '-', ''), 1, 11));
  v_org_code := v_org_code_prefix || '_' || v_org_code_suffix;

  -- Explicit table alias required: RETURNS TABLE declares an implicit
  -- plpgsql variable named organisation_id, which would otherwise make a
  -- bare "RETURNING organisation_id" ambiguous against that variable.
  INSERT INTO gov_repo.organisations AS inserted_org (
    organisation_id,
    org_code,
    legal_name,
    display_name,
    country_code,
    is_active
  ) VALUES (
    v_org_id,
    v_org_code,
    p_org_name,
    p_org_name,
    'PT',
    true
  )
  RETURNING inserted_org.organisation_id INTO v_org_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Failed to create organisation';
  END IF;

  -- ===========================================================================
  -- STEP 2: Create governance user
  -- ===========================================================================
  -- Explicit table alias required: RETURNS TABLE declares an implicit
  -- plpgsql variable named user_id, which would otherwise make a bare
  -- "RETURNING user_id" ambiguous against that variable.
  INSERT INTO gov_repo.governance_users AS inserted_user (
    email,
    full_name,
    display_name,
    organisation_id,
    status,
    external_id,
    role_ids
  ) VALUES (
    p_email,
    p_full_name,
    p_full_name,
    v_org_id,
    'active',
    p_password_hash,
    ARRAY[v_admin_role_id]::uuid[]
  )
  RETURNING inserted_user.user_id INTO v_user_id;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Failed to create user';
  END IF;

  -- ===========================================================================
  -- RETURN: Non-secret identity/session bootstrap data only
  -- ===========================================================================
  RETURN QUERY
  SELECT
    gu.user_id,
    gu.email,
    gu.full_name,
    go.organisation_id,
    go.legal_name as organisation_name,
    v_admin_role_id as role_id,
    v_admin_role_code::varchar as role_code
  FROM gov_repo.governance_users gu
  JOIN gov_repo.organisations go ON gu.organisation_id = go.organisation_id
  WHERE gu.user_id = v_user_id
  LIMIT 1;

  -- If we reach here, all steps succeeded.
  -- Caller COMMIT makes it durable; caller ROLLBACK on error atomically undoes everything.
END;
$$;

-- =============================================================================
-- COMMENT: Documentation
-- =============================================================================
COMMENT ON FUNCTION gov_repo.signup_legacy IS
'ATOMIC legacy signup: creates organisation + user + GOVERNANCE_ADMIN role assignment in a single transaction.
SECURITY INVOKER - caller must be service_role.
org_code is generated entirely inside this function (readable prefix + suffix derived from the generated organisation_id) — the caller has no org_code authority.
Returns ONLY non-secret identity data.
FAIL CLOSED: any exception rolls back ALL changes.';

-- =============================================================================
-- PERMISSIONS: Restrict EXECUTE to service_role ONLY
-- =============================================================================

-- Revoke from everyone by default
REVOKE ALL ON FUNCTION gov_repo.signup_legacy FROM PUBLIC;
REVOKE ALL ON FUNCTION gov_repo.signup_legacy FROM anon;
REVOKE ALL ON FUNCTION gov_repo.signup_legacy FROM authenticated;

-- Grant EXECUTE only to service_role
GRANT EXECUTE ON FUNCTION gov_repo.signup_legacy TO service_role;

-- =============================================================================
-- SECURITY SUMMARY:
-- =============================================================================
-- 1. SECURITY INVOKER: No privilege escalation; uses caller's rights
-- 2. Explicit SET search_path: gov_repo, pg_catalog only (no public)
-- 3. EXECUTE granted ONLY to service_role
-- 4. REVOKE from: public, anon, authenticated
-- 5. No dynamic SQL; all identifiers fully qualified in-body where needed
-- 6. p_password_hash NOT returned in result
-- 7. external_id (containing hash) NOT selected in return query
-- 8. Transaction atomicity: caller's ROLLBACK undoes organisation AND user
-- 9. Concurrent duplicate email: fails via existing UNIQUE constraint on email
-- 10. org_code: generated ENTIRELY inside this function (readable prefix
--     derived from p_org_name + 11-hex-char suffix derived from this
--     function's own freshly generated organisation_id). The caller has NO
--     authority over org_code and cannot supply or override it — there is
--     no p_org_code parameter. UNIQUE(org_code) remains the final
--     invariant; this is a collision-resistance measure, not a
--     probabilistic uniqueness guarantee. On the astronomically unlikely
--     event of a collision, the INSERT raises and the whole transaction
--     (org + user) rolls back atomically — no orphan, no retry loop.
-- 11. role_id is returned alongside role_code so the caller can independently
--     re-verify admin elevation via a privileged role lookup rather than
--     trusting this function's role_code string alone.
-- 12. Organisation industry classification is intentionally OUT OF SCOPE:
--     canonical gov_repo.organisations has no column for it, so this
--     function accepts no industry parameter and persists nothing for it.
--     Durable industry persistence is a separate domain/data-model decision.
-- =============================================================================
