create or replace function gov_repo.ict_incident_impact_summary(p_incident_id uuid)
returns table(incident_id uuid,incident_code varchar,title varchar,severity gov_repo.incident_severity,total_downtime_mins integer,rto_breach boolean,rpo_breach boolean,services_affected bigint,critical_services_down bigint,ai_systems_affected bigint,agents_affected bigint,providers_affected bigint,clients_affected_total bigint,financial_impact_eur numeric,pii_data_exposed boolean,notifications_sent bigint,notifications_overdue bigint,recovery_progress_pct integer,has_lessons_learned boolean)
language sql security definer as $$ select i.incident_id,i.incident_code,i.title,i.severity,i.downtime_minutes,i.rto_breach,i.rpo_breach,(select count(*) from gov_repo.ict_incident_affected_services s where s.incident_id=i.incident_id),(select count(*) from gov_repo.ict_incident_affected_services s where s.incident_id=i.incident_id and s.ict_function_type in ('critical','important') and s.service_impact='full_outage'),(select count(distinct s.ai_system_id) from gov_repo.ict_incident_affected_services s where s.incident_id=i.incident_id and s.ai_system_id is not null),cardinality(i.impacted_agent_ids),cardinality(i.impacted_provider_ids),(select coalesce(sum(s.clients_affected),0) from gov_repo.ict_incident_affected_services s where s.incident_id=i.incident_id),coalesce(i.financial_impact_eur,0),i.pii_data_exposed,(select count(*) from gov_repo.ict_incident_notifications n where n.incident_id=i.incident_id),(select count(*) from gov_repo.ict_incident_notifications n where n.incident_id=i.incident_id and n.is_breached=true),case i.recovery_status when 'not_started' then 0 when 'containment_active' then 15 when 'eradication_active' then 35 when 'recovery_active' then 55 when 'restored_partial' then 70 when 'restored_full' then 85 when 'monitoring_period' then 90 when 'lessons_learned_pending' then 95 when 'closed' then 100 else 0 end,(i.lessons_learned is not null) from gov_repo.ict_incidents i where i.incident_id=p_incident_id; $$;
insert into gov_repo.mandates(mandate_code,regulation,section_ref,title,requirement_text,requirement_type,effective_date,applicability,mapped_controls) values
('DORA-ART-17','DORA (EU 2022/2554)','Art. 17','ICT-Related Incident Management Process','Financial entities shall define, establish and implement an ICT-related incident management process.','mandatory','2025-01-17','{"sectors":["banking","insurance","investment_firm","payment_institution"]}',array['CG-AG-008','CG-AG-011']),
('DORA-ART-18','DORA (EU 2022/2554)','Art. 18','Classification of ICT-Related Incidents','Financial entities shall classify ICT-related incidents using harmonised criteria.','mandatory','2025-01-17','{"sectors":["banking","insurance","investment_firm","payment_institution"]}',array['CG-AG-010']),
('DORA-ART-19','DORA (EU 2022/2554)','Art. 19','Reporting of Major ICT-Related Incidents','Financial entities shall report major ICT incidents to the competent authority using prescribed timelines.','mandatory','2025-01-17','{"sectors":["banking","insurance","investment_firm","payment_institution"]}',array['CG-AG-008']),
('DORA-ART-20','DORA (EU 2022/2554)','Art. 20','Harmonisation of Reporting Content and Timelines','Financial entities must use approved technical standards and templates for DORA reports.','mandatory','2025-01-17','{"sectors":["banking","insurance","investment_firm","payment_institution"]}',array['CG-AG-008']),
('DORA-ART-21','DORA (EU 2022/2554)','Art. 21','Voluntary Notification of Significant Cyber Threats','Financial entities may voluntarily notify significant cyber threats.','recommended','2025-01-17','{"sectors":["banking","insurance","investment_firm","payment_institution"]}',array['CG-AG-010']),
('NIST-RESPOND-1-1','NIST AI RMF 1.0','RESPOND 1.1','Incident Response Policies and Procedures','Policies, procedures and practices are in place to address AI risks during deployment and use.','recommended','2023-01-26','{"sectors":["all"]}',array['CG-AG-007','CG-AG-008','CG-AG-012']),
('NIST-RESPOND-2-1','NIST AI RMF 1.0','RESPOND 2.1','Incident Containment and Recovery','Responses to AI risks and incidents are communicated and lessons learned reflected in governance.','recommended','2023-01-26','{"sectors":["all"]}',array['CG-AG-008','CG-AG-010']),
('ISO42001-8-2','ISO/IEC 42001:2023','Clause 8.2','AI System Incident Management','The organisation shall establish and maintain an AI incident management process.','mandatory','2023-12-18','{"sectors":["all"]}',array['CG-AG-008','CG-AG-010','CG-AG-012']),
('ISO27001-A-5-24','ISO/IEC 27001:2022','A.5.24','Information Security Incident Management Planning and Preparation','The organisation shall plan and prepare for managing information security incidents.','mandatory','2022-10-25','{"sectors":["all"]}',array['CG-AG-008']),
('ISO27001-A-5-26','ISO/IEC 27001:2022','A.5.26','Response to Information Security Incidents','Incidents shall be responded to in accordance with documented procedures.','mandatory','2022-10-25','{"sectors":["all"]}',array['CG-AG-008']) on conflict(mandate_code) do nothing;
grant execute on function gov_repo.compute_dora_reporting_deadlines to service_role;grant execute on function gov_repo.sync_ai_system_incident_count to service_role;grant execute on function gov_repo.ict_incident_classify_major to service_role,authenticated;grant execute on function gov_repo.ict_dora_sla_status to service_role,authenticated;grant execute on function gov_repo.ict_incident_impact_summary to service_role,authenticated;;
