create or replace view gov_repo.v_control_maturity_summary as
select ca.organisation_id,ca.control_ref,
(select maturity_level from gov_repo.control_assessments ca2 where ca2.control_ref=ca.control_ref and ca2.organisation_id=ca.organisation_id and ca2.status='completed' order by ca2.period_end desc limit 1) as current_maturity,
(select operating_effectiveness from gov_repo.control_assessments ca2 where ca2.control_ref=ca.control_ref and ca2.organisation_id=ca.organisation_id and ca2.status='completed' order by ca2.period_end desc limit 1) as current_operating_effectiveness,
count(*) as total_assessments,max(ca.period_end) as last_assessed,
(select next_assessment_date from gov_repo.control_assessments ca2 where ca2.control_ref=ca.control_ref and ca2.organisation_id=ca.organisation_id and ca2.status='completed' order by ca2.period_end desc limit 1) as next_assessment_date
from gov_repo.control_assessments ca group by ca.organisation_id,ca.control_ref;
comment on view gov_repo.v_control_maturity_summary is 'Current maturity level per CG-AGF control per organisation, derived from latest completed assessment.';
create or replace view gov_repo.v_risk_heatmap as select r.organisation_id,r.likelihood,r.impact,r.inherent_risk_score,count(*) as risk_count,array_agg(r.risk_code order by r.inherent_risk_score desc) as risk_codes,case when r.inherent_risk_score >=20 then 'critical' when r.inherent_risk_score>=12 then 'high' when r.inherent_risk_score>=6 then 'medium' else 'low' end as risk_band from gov_repo.risk_entries r where r.status not in ('closed') group by r.organisation_id,r.likelihood,r.impact,r.inherent_risk_score;
comment on view gov_repo.v_risk_heatmap is 'Risk matrix data for dashboard heatmap visualisation. Grouped by likelihood × impact cell.';
create or replace view gov_repo.v_ledger_recent as select l.entry_sequence,l.event_type,l.event_description,l.subject_type,l.subject_id,u.full_name as actor_name,u.email as actor_email,l.event_timestamp,l.organisation_id,l.entry_hash,l.qes_anchor is not null as is_anchored from gov_repo.governance_ledger l join gov_repo.governance_users u on u.user_id=l.actor_user_id;
comment on view gov_repo.v_ledger_recent is 'Governance ledger with actor details. Use for audit trail display. Filter by organisation_id.';
create or replace view gov_repo.v_mandate_compliance as select m.mandate_id,m.mandate_code,m.regulation,m.section_ref,m.title,m.requirement_type,m.mapped_controls,m.compliance_status,m.last_assessed,(select count(distinct ca.control_ref) from gov_repo.control_assessments ca where ca.control_ref=any(m.mapped_controls) and ca.status='completed') as controls_assessed,array_length(m.mapped_controls,1) as total_controls,(select count(*) from gov_repo.exceptions ex where ex.control_ref=any(m.mapped_controls) and ex.status='active') as active_exceptions_on_controls from gov_repo.mandates m;
comment on view gov_repo.v_mandate_compliance is 'Regulatory mandate compliance status with control assessment coverage and active exceptions.';
create or replace view gov_repo.v_evidence_expiry as select e.evidence_id,e.evidence_code,e.title,e.evidence_type,e.status,e.retention_class,e.retention_until,e.retention_until-current_date as days_to_expiry,e.retention_until<=current_date+60 as expiring_in_60d,e.retention_until<=current_date as is_expired,e.control_refs,e.agent_refs,e.organisation_id,cu.full_name as collected_by_name,vu.full_name as verified_by_name from gov_repo.evidence e join gov_repo.governance_users cu on cu.user_id=e.collected_by left join gov_repo.governance_users vu on vu.user_id=e.verified_by where e.retention_class<>'legal_hold' and e.status not in ('superseded','rejected','expired');
comment on view gov_repo.v_evidence_expiry is 'Evidence retention dashboard. expiring_in_60d flags evidence needing renewal action.';
create or replace function gov_repo.compute_governance_score(p_organisation_id uuid)
returns table (organisation_id uuid,policy_score numeric,risk_score numeric,evidence_score numeric,exception_score numeric,control_maturity_score numeric,total_score numeric,grade char(1))
language sql security definer as $$
with policy_calc as (select coalesce(round(count(*) filter(where status='approved')::numeric/nullif(count(*),0)*100,1),0) as score from gov_repo.governance_policies where organisation_id=p_organisation_id),
risk_calc as (select coalesce(round(count(*) filter(where status in ('treated','monitored','accepted','closed'))::numeric/nullif(count(*),0)*100,1),0) as score from gov_repo.risk_entries where organisation_id=p_organisation_id),
evidence_calc as (select coalesce(round(count(*) filter(where status in ('verified','linked'))::numeric/nullif(count(*),0)*100,1),0) as score from gov_repo.evidence where organisation_id=p_organisation_id),
exception_calc as (select coalesce(100-round(count(*) filter(where status='active')::numeric/nullif(count(*),0)*100,1),100) as score from gov_repo.exceptions where organisation_id=p_organisation_id),
maturity_calc as (select coalesce(round(avg(maturity_level)*20,1),0) as score from (select distinct on(control_ref) control_ref,maturity_level from gov_repo.control_assessments where organisation_id=p_organisation_id and status='completed' order by control_ref,period_end desc) latest)
select p_organisation_id,p.score,r.score,e.score,ex.score,m.score,round((p.score+r.score+e.score+ex.score+m.score)/5,1),case when round((p.score+r.score+e.score+ex.score+m.score)/5,1)>=95 then 'A' when round((p.score+r.score+e.score+ex.score+m.score)/5,1)>=85 then 'B' when round((p.score+r.score+e.score+ex.score+m.score)/5,1)>=70 then 'C' when round((p.score+r.score+e.score+ex.score+m.score)/5,1)>=50 then 'D' else 'F' end::char(1) from policy_calc p,risk_calc r,evidence_calc e,exception_calc ex,maturity_calc m; $$;
comment on function gov_repo.compute_governance_score is 'Computes the organisation governance score (0-100) with letter grade. Grades: A≥95 | B≥85 | C≥70 | D≥50 | F<50. Banking minimum: B (85). ECB target: A (95).';
grant usage on schema gov_repo to authenticated,service_role,anon;
grant execute on function gov_repo.ledger_append to service_role;
grant execute on function gov_repo.ledger_verify to service_role,authenticated;
grant execute on function gov_repo.compute_governance_score to service_role,authenticated;;
