comment on column gov_repo.organisations.organisation_id is 'Canonical identifier of the organisation that acts as the root tenant for governance data.';
comment on column gov_repo.organisations.org_code is 'Unique business code used to identify the organisation independently of its generated tenant identifier.';
comment on column gov_repo.organisations.legal_name is 'Legal name recorded for the regulated entity or organisational unit represented by this tenant.';
comment on column gov_repo.organisations.display_name is 'Human-readable organisation name intended for presentation independently of its legal name.';
comment on column gov_repo.organisations.country_code is 'Two-character country code recorded for the organisation.';
comment on column gov_repo.organisations.is_active is 'Indicates whether the organisation is active in the governance repository; TRUE represents active and FALSE represents inactive.';
comment on column gov_repo.organisations.created_at is 'Timestamp when the organisation was first registered as a tenant in the governance repository.';
comment on column gov_repo.organisations.updated_at is 'Timestamp of the most recent update to the organisation record, maintained by the organisation update trigger.';

comment on column gov_repo.governance_users.user_id is 'Canonical identifier of the governance user within the repository.';
comment on column gov_repo.governance_users.external_id is 'Optional application-supplied value associated with the governance user. The database does not enforce a source, format, uniqueness, or referential contract.';
comment on column gov_repo.governance_users.email is 'Email address associated with the governance user and constrained to be unique across gov_repo.governance_users.';
comment on column gov_repo.governance_users.full_name is 'Full name recorded for the governance user''s organisational identity.';
comment on column gov_repo.governance_users.display_name is 'Human-readable name used to present the governance user independently of the recorded full name.';
comment on column gov_repo.governance_users.organisation_id is 'Identifier of the root tenant organisation that owns and scopes this governance-user record.';
comment on column gov_repo.governance_users.department is 'Department recorded as part of the governance user''s organisational profile.';
comment on column gov_repo.governance_users.job_title is 'Job title recorded as part of the governance user''s organisational profile.';
comment on column gov_repo.governance_users.status is 'Lifecycle state of the governance user, using the values active, suspended, pending, or deactivated.';
comment on column gov_repo.governance_users.preferred_mfa is 'Legacy, unused, non-authoritative field retained for the governance user''s preferred multi-factor authentication method. It does not represent factor enrollment, factor verification, authentication enforcement, authorization authority, or identity-provider synchronization authority.';
comment on column gov_repo.governance_users.created_at is 'Timestamp when the governance-user record was created.';
comment on column gov_repo.governance_users.updated_at is 'Timestamp of the most recent update to the governance-user record, maintained by the user update trigger.';
comment on column gov_repo.governance_users.last_login_at is 'Timestamp of the most recent login recorded for the governance user.';
comment on column gov_repo.governance_users.password_changed_at is 'Timestamp of the most recent password-change event recorded for the governance user.';

comment on column gov_repo.governance_roles.role_id is 'Canonical identifier of the governance RBAC role definition.';
comment on column gov_repo.governance_roles.role_code is 'Unique machine-readable code that identifies the governance role independently of its display name.';
comment on column gov_repo.governance_roles.role_name is 'Human-readable name assigned to the governance role.';
comment on column gov_repo.governance_roles.role_description is 'Description of the governance purpose and responsibilities represented by the role.';
comment on column gov_repo.governance_roles.role_tier is 'Scope tier assigned to the governance role, constrained to system, organisation, department, or agent.';
comment on column gov_repo.governance_roles.can_approve_up_to is 'Legacy, unused, non-authoritative textual field retained on a governance role. It does not define authorization, approval authority, workflow authorization, a role hierarchy, or an approval limit; structured permissions and workflows are authoritative.';
comment on column gov_repo.governance_roles.is_system_role is 'Indicates whether the governance role is classified as a system role.';
comment on column gov_repo.governance_roles.created_at is 'Timestamp when the governance-role definition was created.';

comment on column gov_repo.governance_ledger.entry_sequence is 'Primary sequence value used to identify and order governance-ledger entries.';
comment on column gov_repo.governance_ledger.entry_id is 'Generated UUID reference for a governance-ledger entry; entry_sequence remains the primary ordering key.';
comment on column gov_repo.governance_ledger.event_type is 'Application-supplied category of the governance event recorded in the ledger.';
comment on column gov_repo.governance_ledger.event_description is 'Human-readable description supplied for the governance event.';
comment on column gov_repo.governance_ledger.subject_type is 'Type discriminator for the governed subject to which the ledger event applies.';
comment on column gov_repo.governance_ledger.subject_id is 'Identifier of the governed subject, interpreted together with subject_type because the ledger records events for multiple subject kinds.';
comment on column gov_repo.governance_ledger.actor_user_id is 'Identifier of the governance user attributed as the actor for the ledger event.';
comment on column gov_repo.governance_ledger.actor_ip is 'Network address attributed to the actor when the governance event is recorded.';
comment on column gov_repo.governance_ledger.actor_session_id is 'Deprecated legacy UUID field retained for actor-session context. It has no current producer or consumer and must not be used as authentication-session identity, authorization authority, JWT or session authority, actor identity authority, or ledger-integrity evidence.';
comment on column gov_repo.governance_ledger.organisation_id is 'Tenant organisation under which the governance-ledger event is recorded and queried.';
comment on column gov_repo.governance_ledger.event_timestamp is 'Timestamp assigned to the governance event for chronological reporting; the ledger append function assigns its append-time value.';
comment on column gov_repo.governance_ledger.recorded_at is 'Timestamp at which the ledger entry is recorded and bound into its cryptographic hash-chain input.';
comment on column gov_repo.governance_ledger.payload is 'Event-specific JSON payload preserved as part of the ledger entry and its cryptographic hash input; its structure depends on event_type.';
comment on column gov_repo.governance_ledger.qes_anchor_at is 'Timestamp recorded when the RFC 3161 timestamp token stored in qes_anchor was attached to the ledger entry.';

comment on column gov_repo.governance_policies.policy_id is 'Canonical identifier of the governance policy.';
comment on column gov_repo.governance_policies.policy_code is 'Organisation-scoped business code used to identify the governance policy independently of its generated identifier.';
comment on column gov_repo.governance_policies.title is 'Human-readable title of the governance policy.';
comment on column gov_repo.governance_policies.description is 'Summary describing the purpose or scope of the governance policy.';
comment on column gov_repo.governance_policies.policy_type is 'Governance-policy category, using the values operational, risk, security, data, ethics, or compliance.';
comment on column gov_repo.governance_policies.status is 'Lifecycle state of the governance policy, using the values draft, in_review, approved, deprecated, or superseded.';
comment on column gov_repo.governance_policies.effective_date is 'Date from which the governance policy is recorded as effective.';
comment on column gov_repo.governance_policies.expiry_date is 'Optional date after which the governance policy is recorded as expired. When both expiry_date and effective_date are present, expiry_date must be later than effective_date.';
comment on column gov_repo.governance_policies.owner_user_id is 'Governance user assigned as the owner of the policy.';
comment on column gov_repo.governance_policies.approver_user_id is 'Governance user designated as the policy approver; the value may remain absent until an approver is assigned.';
comment on column gov_repo.governance_policies.organisation_id is 'Identifier of the root tenant organisation that owns and scopes the governance policy.';
comment on column gov_repo.governance_policies.created_at is 'Timestamp when the governance-policy master record was created.';
comment on column gov_repo.governance_policies.updated_at is 'Timestamp of the most recent update to the governance-policy master record, maintained by the policy update trigger.';
comment on column gov_repo.governance_policies.created_by is 'Governance user who created the policy master record.';

comment on column gov_repo.policy_versions.version_id is 'Canonical identifier of a specific governance-policy version.';
comment on column gov_repo.policy_versions.policy_id is 'Governance policy to which this version belongs.';
comment on column gov_repo.policy_versions.version_number is 'Integer version number that uniquely identifies this version within its governance policy.';
comment on column gov_repo.policy_versions.version_label is 'Human-readable label assigned to the policy version in addition to its numeric version number.';
comment on column gov_repo.policy_versions.content_markdown is 'Markdown-formatted policy content preserved for this specific policy version.';
comment on column gov_repo.policy_versions.change_summary is 'Summary of the changes represented by this policy version.';
comment on column gov_repo.policy_versions.status is 'Approval-workflow state of the policy version, using the values draft, under_review, approved, rejected, or superseded.';
comment on column gov_repo.policy_versions.reviewed_by is 'Governance user recorded as the reviewer of this policy version.';
comment on column gov_repo.policy_versions.approved_by is 'Governance user who approved this policy version.';
comment on column gov_repo.policy_versions.approval_date is 'Timestamp when approval of this policy version was recorded.';
comment on column gov_repo.policy_versions.qes_signature_id is 'Optional reference to a gov_repo.qes_signatures record associated with this policy version.';
comment on column gov_repo.policy_versions.ledger_entry_seq is 'Governance-ledger sequence associated with the policy-version event.';
comment on column gov_repo.policy_versions.created_at is 'Timestamp when this policy-version record was created.';
comment on column gov_repo.policy_versions.created_by is 'Governance user who created this policy version.';

comment on column gov_repo.mandates.mandate_id is 'Canonical identifier of the catalogued regulatory or standards mandate.';
comment on column gov_repo.mandates.mandate_code is 'Unique repository code used to identify the mandate independently of its generated identifier.';
comment on column gov_repo.mandates.regulation is 'Regulatory or standards source from which the mandate is catalogued.';
comment on column gov_repo.mandates.section_ref is 'Section or article reference locating the mandate within its regulatory or standards source.';
comment on column gov_repo.mandates.title is 'Human-readable title of the catalogued mandate.';
comment on column gov_repo.mandates.requirement_text is 'Repository text describing the requirement represented by the mandate.';
comment on column gov_repo.mandates.requirement_type is 'Requirement classification of the mandate, using the values mandatory, recommended, or conditional.';
comment on column gov_repo.mandates.effective_date is 'Date on which the catalogued mandate becomes effective.';
comment on column gov_repo.mandates.applicability is 'JSON object containing conditions recorded to describe when the mandate applies. The database does not enforce a schema for these conditions; an empty object contains no encoded conditions.';
comment on column gov_repo.mandates.mapped_policies is 'Legacy, denormalized, non-authoritative array of policy identifiers associated with the mandate. Canonical policy-to-mandate relationships are represented by gov_repo.policy_mandate_mappings.';
comment on column gov_repo.mandates.organisation_id is 'Optional tenant organisation that owns the mandate record; NULL identifies a system-wide mandate available across tenants.';
comment on column gov_repo.mandates.compliance_status is 'Recorded assessment state of the mandate, using the values not_assessed, partial, compliant, or non_compliant.';
comment on column gov_repo.mandates.last_assessed is 'Date of the most recent assessment recorded for the mandate.';
comment on column gov_repo.mandates.created_at is 'Timestamp when the mandate record was created in the repository.';

comment on table gov_repo.policy_mandate_mappings is 'Associates a governance policy with a regulatory or standards mandate and records the declared coverage between them; only one mapping is permitted for each policy and mandate pair.';
comment on column gov_repo.policy_mandate_mappings.mapping_id is 'Canonical identifier of the association between a governance policy and a mandate.';
comment on column gov_repo.policy_mandate_mappings.policy_id is 'Governance policy participating in this policy-to-mandate association.';
comment on column gov_repo.policy_mandate_mappings.mandate_id is 'Regulatory or standards mandate participating in this policy-to-mandate association.';
comment on column gov_repo.policy_mandate_mappings.coverage_level is 'Declared extent to which the governance policy covers the mandate. New mappings default to partial; the database does not enforce a closed vocabulary.';
comment on column gov_repo.policy_mandate_mappings.notes is 'Optional explanatory notes about the policy-to-mandate coverage mapping.';
comment on column gov_repo.policy_mandate_mappings.created_at is 'Timestamp when the policy-to-mandate association was created.';
